"""Application constants shared by backend modules."""

APP_VERSION_DEFAULT = "2.6.3-beta.3"
UPDATE_REPOSITORY = "salvetum/SifreKasam"
UPDATE_RELEASE_API = f"https://api.github.com/repos/{UPDATE_REPOSITORY}/releases/latest"

SECRET_PLACEHOLDER = "__SECRET__"
MAX_BULK_IDS = 500
MAX_IMPORT_RECORDS = 5000
VALID_RECORD_TYPES = {"Website", "Application", "CreditCard", "SecureNote", "Other"}
DEFAULT_CATEGORY = "Genel"

DEFAULT_ACCENT_COLOR = "#7c6ff7"
DEFAULT_BACKGROUND_STYLE = "aurora"
VALID_BACKGROUND_STYLES = {"aurora", "midnight", "mesh", "plain", "custom"}
CUSTOM_BACKGROUND_MAX_IMAGE_BYTES = 10 * 1024 * 1024
CUSTOM_BACKGROUND_MAX_GIF_BYTES = 20 * 1024 * 1024
CUSTOM_BACKGROUND_HISTORY_LIMIT = 8
DEFAULT_CHROMA_ACCENT_ENABLED = False
DEFAULT_CHROMA_ACCENT_SPEED = 15
VALID_CHROMA_ACCENT_SPEEDS = {8, 15, 30, 60}
DEFAULT_GLASS_QUALITY = "normal"
VALID_GLASS_QUALITIES = {"low", "normal", "high"}
VALID_THEME_MODES = {"light", "dark", "system"}
DEFAULT_THEME_MODE = "dark"
DEFAULT_ANIMATED_BACKGROUNDS_ENABLED = True
DEFAULT_INTERFACE_ANIMATIONS_ENABLED = True
DEFAULT_GRADIENTS_ENABLED = True
DEFAULT_CARD_SHEEN_ENABLED = True
DEFAULT_CARD_FRAME_ENABLED = True
DEFAULT_CARD_DEPTH_ENABLED = True
DEFAULT_CONTENT_PROTECTION_ENABLED = False
DEFAULT_HARDWARE_ACCELERATION_ENABLED = True

LEGACY_PBKDF2_SALT = b"kasa_masaustu_salt_12345"
PBKDF2_SALT_SETTING = "pbkdf2_salt_b64"
PBKDF2_ITERATIONS = 600_000
LEGACY_PBKDF2_ITERATIONS = 100_000
RECORD_METADATA_PREFIX = "sifrekasam:v1:"
RECORD_METADATA_SETTING = "record_metadata_encryption_v1"
RECORD_METADATA_FIELDS = ("title", "website_url", "login")
